package com.test.fitnessstudios.helpers

object Constants {

    const val DEFAULT_LATITUDE=33.524155
    const val DEFAULT_LONGITUDE=-111.905792
    const val LAST_TAB_POSITION="LAST_TAB_POSITION"
    const val USER_PREFERENCES="USER_PREFERENCES"
    const val TAG_STUDIO_DETAIL_FRAGMENT="TAG_STUDIO_DETAIL_FRAGMENT"
    const val KEY_SELECTED_STUDIO="KEY_SELECTED_STUDIO"
}
